### ISSUE TITLE
AttributeError: set_new_allowed

### ISSUE THREAD

**Issue by sustech-lz** [zhouc20/LatentGraphDiffusion#2]
cfg.name_tag = ""
这个参数有没有建议的设置呢？

**Comment by sustech-lz** [comment]
Traceback (most recent call last):
  File "/home/lz/LatentGraphDiffusion/pretrain.py", line 257, in <module>
    custom_set_out_dir(cfg, args.cfg_file, cfg.name_tag)
  File "/home/lz/anaconda3/envs/digress/lib/python3.9/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: name_tag
我安装0.1.8版本的时候，是这样的报错

**Comment by zhouc20** [comment]
This is not an error in the package. You just need to specify the name_tag argument. You can choose whatever name tag you want for the experiment.
